# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm" # Replace with your package manager (e.g., "maven" for Java, "pip" for Python)
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily" # Frequency of updates ("daily", "weekly", etc.)
    open-pull-requests-limit: 10 # Maximum number of open pull requests
  - package-ecosystem: "pip" # Add your second package manager here
    directory: "/" # And the location of its package manifests
    schedule:
      interval: "weekly" # Choose how often to check for updates
