# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm" # JavaScript
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
  - package-ecosystem: "pip" # Python
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "maven" # Java
    directory: "/" # Update this if your pom.xml is not in the root directory
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget" # .NET
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "composer" # PHP
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "rubygems" # Ruby
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cocoapods" # iOS
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gradle" # Android/Java
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo" # Rust
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker" # Docker
    directory: "/"
    schedule:
      interval: "weekly"
